# Generated by Django 5.2.1 on 2025-06-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regroupements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regroupements', to='core.groupe')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regroupements', to='core.membre')),
            ],
            options={
                'verbose_name': 'Regroupement',
                'verbose_name_plural': 'Regroupements',
                'unique_together': {('membre', 'groupe')},
            },
        ),
    ]
