# Generated by Django 5.0.7 on 2025-06-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_libelle_tag_name_remove_tag_description_and_more'),
    ]

    operations = [
        # Ajouter la contrainte d'unicité sur le nom du groupe
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        # Ajouter la contrainte d'unicité sur la combinaison nom/prénom du membre
        migrations.AlterUniqueTogether(
            name='membre',
            unique_together={('nom', 'prenom')},
        ),
    ]
