# Generated by Django 5.0.7 on 2025-06-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250630_1805'),
    ]

    operations = [
        # Ajouter la contrainte d'unicité sur le nom du département
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        # Créer le modèle Serviteurs
        migrations.CreateModel(
            name='Serviteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('is_responsable', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviteurs', to='core.departement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviteurs', to='core.membre')),
            ],
            options={
                'verbose_name': 'Serviteur',
                'verbose_name_plural': 'Serviteurs',
                'unique_together': {('membre', 'departement')},
            },
        ),
    ]
