// Configuration des variables d'environnement
export const config = {
  // URL de l'API backend
  API_URL: import.meta.env.VITE_API_URL || 'http://localhost:8000',
  
  // Configuration de l'environnement
  NODE_ENV: import.meta.env.VITE_NODE_ENV || 'development',
  
  // Configuration de l'application
  APP_NAME: 'Harvest Management',
  APP_VERSION: '1.0.0',
  
  // Configuration des timeouts
  API_TIMEOUT: 10000,
  
  // Configuration des endpoints
  ENDPOINTS: {
    AUTH: {
      LOGIN: '/api/login',
    //   REGISTER: '/api/auth/register/',
      LOGOUT: '/api/logout',
      USER: '/api/verify-token',
      REFRESH: '/api/verify-token',
      RESET_PASSWORD: '/api/reset-password',
    },
    MEMBERS: {
      LIST: '/api/members/',
      CREATE: '/api/members/',
      DETAIL: (id: number) => `/api/members/${id}/`,
      UPDATE: (id: number) => `/api/members/${id}/`,
      DELETE: (id: number) => `/api/members/${id}/`,
      SEARCH: '/api/members/search/',
      STATISTICS: '/api/members/statistics/',
      EXPORT: '/api/members/export/',
      IMPORT: '/api/members/import/',
    },
    EVENTS: {
      LIST: '/api/events/',
      CREATE: '/api/events/',
      DETAIL: (id: number) => `/api/events/${id}/`,
      UPDATE: (id: number) => `/api/events/${id}/`,
      DELETE: (id: number) => `/api/events/${id}/`,
      SEARCH: '/api/events/search/',
      UPCOMING: '/api/events/upcoming/',
      PAST: '/api/events/past/',
      REGISTER: '/api/events/register/',
      UNREGISTER: (id: string) => `/api/events/${id}/unregister/`,
      ATTENDEES: (id: string) => `/api/events/${id}/attendees/`,
      EXPORT: '/api/events/export/',
      DUPLICATE: (id: string) => `/api/events/${id}/duplicate/`,
      CANCEL: (id: string) => `/api/events/${id}/cancel/`,
      REACTIVATE: (id: string) => `/api/events/${id}/reactivate/`,
      REMINDERS: (id: string) => `/api/events/${id}/reminders/`,
    },
    APPOINTMENTS: {
      LIST: '/api/appointments/',
      CREATE: '/api/appointments/',
      DETAIL: (id: number) => `/api/appointments/${id}/`,
      UPDATE: (id: number) => `/api/appointments/${id}/`,
      DELETE: (id: number) => `/api/appointments/${id}/`,
      SEARCH: '/api/appointments/search/',
      TODAY: '/api/appointments/today/',
      WEEK: '/api/appointments/week/',
      MONTH: '/api/appointments/month/',
      CONFIRM: (id: string) => `/api/appointments/${id}/confirm/`,
      CANCEL: (id: string) => `/api/appointments/${id}/cancel/`,
      COMPLETE: (id: string) => `/api/appointments/${id}/complete/`,
      RESCHEDULE: (id: string) => `/api/appointments/${id}/reschedule/`,
      CLIENT: (clientId: string) => `/api/appointments/client/${clientId}/`,
      MEMBER: (memberId: number) => `/api/appointments/member/${memberId}/`,
      EXPORT: '/api/appointments/export/',
      REMINDERS: '/api/appointments/reminders/',
      STATISTICS: '/api/appointments/statistics/',
      CHECK_AVAILABILITY: '/api/appointments/check-availability/',
    },
    DEPARTMENTS: {
      LIST: '/api/departments/',
      CREATE: '/api/departments/',
      DETAIL: (id: string) => `/api/departments/${id}/`,
      UPDATE: (id: string) => `/api/departments/${id}/`,
      DELETE: (id: string) => `/api/departments/${id}/`,
      SEARCH: '/api/departments/search/',
      STATISTICS: (id: string) => `/api/departments/${id}/statistics/`,
      MEMBERS: (id: string) => `/api/departments/${id}/members/`,
      ASSIGN_RESPONSIBLE: (id: string) => `/api/departments/${id}/assign-responsible/`,
      REMOVE_RESPONSIBLE: (id: string) => `/api/departments/${id}/remove-responsible/`,
      EXPORT: '/api/departments/export/',
      COLORS: '/api/departments/colors/',
      CHECK_NAME: '/api/departments/check-name/',
    },
    GROUPS: {
      LIST: '/api/groups/',
      CREATE: '/api/groups/',
      DETAIL: (id: string) => `/api/groups/${id}/`,
      UPDATE: (id: string) => `/api/groups/${id}/`,
      DELETE: (id: string) => `/api/groups/${id}/`,
      SEARCH: '/api/groups/search/',
      STATISTICS: (id: string) => `/api/groups/${id}/statistics/`,
      MEMBERS: (id: string) => `/api/groups/${id}/members/`,
      ASSIGN_RESPONSIBLE: (id: string) => `/api/groups/${id}/assign-responsible/`,
      REMOVE_RESPONSIBLE: (id: string) => `/api/groups/${id}/remove-responsible/`,
      ASSIGN_DEPARTMENT: (id: string) => `/api/groups/${id}/assign-department/`,
      REMOVE_DEPARTMENT: (id: string) => `/api/groups/${id}/remove-department/`,
      ADD_MEMBERS: (id: string) => `/api/groups/${id}/add-members/`,
      REMOVE_MEMBERS: (id: string) => `/api/groups/${id}/remove-members/`,
      EXPORT: '/api/groups/export/',
      COLORS: '/api/groups/colors/',
      CHECK_NAME: '/api/groups/check-name/',
    },
    TAGS: {
      LIST: '/api/tags/',
      CREATE: '/api/tags/',
      DETAIL: (id: string) => `/api/tags/${id}/`,
      UPDATE: (id: string) => `/api/tags/${id}/`,
      DELETE: (id: string) => `/api/tags/${id}/`,
      SEARCH: '/api/tags/search/',
      STATISTICS: (id: string) => `/api/tags/${id}/statistics/`,
      MEMBERS: (id: string) => `/api/tags/${id}/members/`,
      CATEGORIES: '/api/tags/categories/',
      BY_CATEGORY: (category: string) => `/api/tags/category/${category}/`,
      POPULAR: '/api/tags/popular/',
      RECENT: '/api/tags/recent/',
      MERGE: '/api/tags/merge/',
      EXPORT: '/api/tags/export/',
      COLORS: '/api/tags/colors/',
      CHECK_NAME: '/api/tags/check-name/',
      SUGGESTIONS: '/api/tags/suggestions/',
    },
    ETAPES: {
      LIST: '/api/etapes/',
      CREATE: '/api/etapes/',
      DETAIL: (id: string) => `/api/etapes/${id}/`,
      UPDATE: (id: string) => `/api/etapes/${id}/`,
      DELETE: (id: string) => `/api/etapes/${id}/`,
      SEARCH: '/api/etapes/search/',
      ORDERED: '/api/etapes/ordered/',
      REORDER: '/api/etapes/reorder/',
      STATISTICS: (id: string) => `/api/etapes/${id}/statistics/`,
      MEMBERS: (id: string) => `/api/etapes/${id}/members/`,
      ASSIGN_MEMBER: (id: string) => `/api/etapes/${id}/assign-member/`,
      REMOVE_MEMBER: (id: string) => `/api/etapes/${id}/remove-member/`,
      COMPLETE: (id: string) => `/api/etapes/${id}/complete/`,
      COLORS: '/api/etapes/colors/',
      CHECK_LIBELLE: '/api/etapes/check-libelle/',
      EXPORT: '/api/etapes/export/',
      DUPLICATE: (id: string) => `/api/etapes/${id}/duplicate/`,
      ACTIVE: '/api/etapes/active/',
      TOGGLE_STATUS: (id: string) => `/api/etapes/${id}/toggle-status/`,
    },
    STATISTICS: {
      DASHBOARD: '/api/statistics/dashboard/',
      USERS: '/api/statistics/users/',
      MEMBERS: '/api/statistics/members/',
      EVENTS: '/api/statistics/events/',
      APPOINTMENTS: '/api/statistics/appointments/',
      GROWTH: '/api/statistics/growth/',
      GEOGRAPHIC: '/api/statistics/geographic/',
      ACTIVITY: '/api/statistics/activity/',
      PERFORMANCE: '/api/statistics/performance/',
      CUSTOM_REPORT: '/api/statistics/custom-report/',
      EXPORT: '/api/statistics/export/',
      ALERTS: '/api/statistics/alerts/',
      MARK_ALERT_READ: (id: string) => `/api/statistics/alerts/${id}/read/`,
      MARK_ALL_ALERTS_READ: '/api/statistics/alerts/mark-all-read/',
    },
  },
  
  // Configuration des messages d'erreur
  ERROR_MESSAGES: {
    NETWORK_ERROR: 'Erreur de connexion au serveur',
    UNAUTHORIZED: 'Vous n\'êtes pas autorisé à accéder à cette ressource',
    FORBIDDEN: 'Accès interdit',
    NOT_FOUND: 'Ressource non trouvée',
    VALIDATION_ERROR: 'Erreur de validation des données',
    SERVER_ERROR: 'Erreur interne du serveur',
    UNKNOWN_ERROR: 'Une erreur inattendue est survenue',
  },
  
  // Configuration des validations
  VALIDATION: {
    PASSWORD_MIN_LENGTH: 8,
    USERNAME_MIN_LENGTH: 3,
    EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  },
} as const;

// Types pour la configuration
export type Config = typeof config;
export type Endpoints = typeof config.ENDPOINTS;
export type ErrorMessages = typeof config.ERROR_MESSAGES; 